include: package:lint/analysis_options.yaml
analyzer:
  errors:
    must_be_immutable: ignore
    invalid_use_of_protected_member: ignore
    require_trailing_commas: ignore
    eol_at_end_of_file: ignore
    type_annotate_public_apis: ignore
